name: T735 Kernel Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Force Install pmbootstrap
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git
          # This flag '--break-system-packages' is the secret sauce for Ubuntu 24.04
          pip3 install --user pmbootstrap --break-system-packages || pip3 install --user pmbootstrap
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          pmbootstrap init <<EOF
          $HOME/.local/var/pmbootstrap
          edge
          samsung
          t735
          n
          rakzn
          EOF
          pmbootstrap build linux-samsung-t735 --force
          pmbootstrap export

      - name: Upload boot.img
        uses: actions/upload-artifact@v4
        with:
          name: T735-Image
          path: /tmp/postmarketOS-export/boot.img-samsung-t735
