name: T735 Kernel Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This is the official "easy mode" tool from the pmOS team
      - name: Setup pmbootstrap
        uses: postmarketos/pmbootstrap-action@v5

      - name: Build T735 Kernel
        run: |
          pmbootstrap init -d samsung -p t735 <<EOF
          edge
          n
          rakzn
          EOF
          pmbootstrap build linux-samsung-t735 --force
          pmbootstrap export

      - name: Upload boot.img
        uses: actions/upload-artifact@v4
        with:
          name: T735-Image
          path: /tmp/postmarketOS-export/boot.img-samsung-t735
